var data1 = [
    {   
        codigo:"cod1",
        titulo:"titulo",
        image: "./assets/interior-1.jpg",
        direccion:"New York",
        camas:"1",
        banos:"1",
        cochera:"si",    
    },
    {   
        codigo:"cod2",
        titulo:"titulo",
        image: "./assets/interior-2.jpg",
        direccion:"Chicago",
        camas:"1",
        banos:"1",
        cochera:"si",    
    },
    {   
        codigo:"cod3",
        titulo:"titulo",
        image: "./assets/interior-3.jpg",
        direccion:"Chicago",
        camas:"1",
        banos:"1",
        cochera:"si",    
    },
    {   
        codigo:"cod4",
        titulo:"titulo",
        image: "./assets/interior-4.jpg",
        direccion:"New York",
        camas:"1",
        banos:"1",
        cochera:"no",    
    },
    {   
        codigo:"cod5",
        titulo:"titulo",
        image: "./assets/interior-5.jpg",
        direccion:"New York",
        camas:"1",
        banos:"1",
        cochera:"si",    
    },
    {   
        codigo:"cod1",
        titulo:"titulo",
        image: "./assets/interior-1.jpg",
        direccion:"Chicago",
        camas:"1",
        banos:"1",
        cochera:"si",    
    },
    {   
        codigo:"cod3",
        titulo:"titulo",
        image: "./assets/interior-3.jpg",
        direccion:"Chicago",
        camas:"1",
        banos:"1",
        cochera:"no",    
    },
    {   
        codigo:"cod4",
        titulo:"titulo",
        image: "./assets/interior-4.jpg",
        direccion:"New York",
        camas:"1",
        banos:"1",
        cochera:"si",    
    },
    {   
        codigo:"cod5",
        titulo:"titulo",
        image: "./assets/interior-5.jpg",
        direccion:"New York",
        camas:"1",
        banos:"1",
        cochera:"si",    
    },
];



var data2 = [
    {   
        codigo:"cod1",
        titulo:"titulo",
        image: "./assets/oficina-1.jpg",
        direccion:"New York",
        camas:"1",
        banos:"1",
        cochera:"si",    
    },
    {   
        codigo:"cod1",
        titulo:"titulo",
        image: "./assets/oficina-2.jpg",
        direccion:"New York",
        camas:"1",
        banos:"1",
        cochera:"si",    
    },
    {   
        codigo:"cod1",
        titulo:"titulo",
        image: "./assets/oficina-3.jpg",
        direccion:"New York",
        camas:"1",
        banos:"1",
        cochera:"si",    
    },
    {   
        codigo:"cod1",
        titulo:"titulo",
        image: "./assets/oficina-4.jpg",
        direccion:"New York",
        camas:"1",
        banos:"1",
        cochera:"si",    
    },
    {   
        codigo:"cod1",
        titulo:"titulo",
        image: "./assets/oficina-1.jpg",
        direccion:"New York",
        camas:"1",
        banos:"1",
        cochera:"si",    
    },
    {   
        codigo:"cod1",
        titulo:"titulo",
        image: "./assets/oficina-2.jpg",
        direccion:"New York",
        camas:"1",
        banos:"1",
        cochera:"si",    
    },
]